name: Docker Build and Push

on:
  push:
    tags:
      - "v*"

jobs:
  build-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 确保获取所有标签历史

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        id: docker_login

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/person-blog:${{ steps.get_tag.outputs.tag }}

      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-docker-ACR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 确保获取所有标签历史

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Alibaba Cloud Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/dxm666/person-blog:${{ steps.get_tag.outputs.tag }}

      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-docker-SWR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Huawei Cloud
      run: docker login -u cn-north-4@HLHK2EZM2D3SXNCK3POM -p 5832611ec0d8c09d7d8c3051722bc75e05ee6b383427d7880cb8161cf75acb6a swr.cn-north-4.myhuaweicloud.com

    - name: Build and Push Docker Image
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: swr.cn-north-4.myhuaweicloud.com/dxm666/person-blog:${{ steps.get_tag.outputs.tag }}
