name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Build React App
      run: npm run build --prefix client
    - name: Build NestJS App
      run: npm run build

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: user/repo:latest, user/repo:${{ github.ref }}
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy-to-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
    - name: Deploy to Kubernetes
      run: kubectl set image deployment/my-deployment my-container=user/repo:${{ github.ref }} --record
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
